[project]
name = "bs-writing-detector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wassname", email = "1103714+wassname@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "anycache>=2.4.0",
    "auto-gptq>=0.7.1",
    "bitsandbytes>=0.46.1",
    "datasets>=4.0.0",
    "einops>=0.8.1",
    "loguru>=0.7.3",
    "matplotlib>=3.10.3",
    "numpy>=2.3.2",
    "openai>=1.97.1",
    "pandas>=2.3.1",
    "peft>=0.16.0",
    "python-frontmatter>=1.1.0",
    "seaborn>=0.13.2",
    "tqdm>=4.67.1",
    "transformers>=4.54.0",
]

[project.scripts]
bs-writing-detector = "bs_writing_detector:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]  # search the root directory
include = ["bs_writing_detector*"]

[dependency-groups]
dev = [
    "ipykernel>=6.30.0",
    "ipywidgets>=8.1.7",
]
